name: 🐞 Bug Report / 💡 Feature Request
description: Report a bug or suggest a feature for the C++ project
title: "[Bug] <short description>" or "[Feature] <short description>"
labels: ["triage"]
assignees: []

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Issue
      options:
        - Bug Report
        - Feature Request
        - Documentation
        - Question
      default: 0
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Compiler, OS, and any relevant dependencies (e.g., GCC 11.2, Ubuntu 22.04)
      placeholder: e.g., MSVC 2022 on Windows 11
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue or feature.
      placeholder: Describe the problem or feature in detail.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (for bugs)
      description: Provide a minimal reproducible example or steps to trigger the issue.
      placeholder: |
        1. Compile with ...
        2. Run with ...
        3. Observe ...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: false

  - type: textarea
    id: code_snippet
    attributes:
      label: Relevant Code or Logs
      description: Paste any relevant code snippets or error messages.
      render: cpp
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates.
          required: true
        - label: I have provided sufficient information for reproduction or understanding.
          required: true
