name: C/C++ CI

on:
  push:
    branches: [ "action" ]
  pull_request:
    branches: [ "action" ]

jobs:
  build:

    runs-on: thinkcentre

    steps:
    - uses: actions/checkout@v4
    - name: Initialzie, update submodules
      run: |
        git submodule update --init --recursive
    - name: make
      run: |
        make  
    - name: Notify on success
      if: success()
      run: echo "Build and tests passed successfully!"

    - name: Notify on failure
      if: failure()
      run: echo "Build or tests failed. Please check the logs."
